

import Head from 'next/head'
import {useEffect, useState} from 'react'
import { useRouter } from 'next/router'

import { getSearch }  from '../../data/seach_data'

import AppBarBar from '../../component/AppBarBar'
import Jumbotron from '../../component/Jumbotron'
import ListItem from '../../component/ListItem'
import { makeStyles } from '@material-ui/core/styles';
import { 
  Grid,
  Typography,
  Card,
  Divider
} from '@material-ui/core';

const useStyles = makeStyles((theme) => ({  
  movieInfo:{
    padding: '0px 100px',
    marginTop: -70,
    [theme.breakpoints.down('sm')]: {
      padding: '0px 16px',      
    },
  },
  movieContainer:{
    [theme.breakpoints.down('sm')]: {    
      justifyContent: 'center',
      textAlign: 'center',
    },
  },
  card:{
    width: 214.54,
    height: 281.54,    
    backgroundColor: 'silver',
    marginBottom: 16,
    marginRight: 8,
    backgroundSize: '100% 100%',
    backgroundPosition: '0% 0%',
    backgroundRepeat: 'no-repeat',
    [theme.breakpoints.down('sm')]: {
      width: 131.33,
      height: 171.73,
      marginBottom: 0,
      marginRight: 0,      
    },
  },
  movieTitle:{
    display: 'flex',
    flexDirection: 'column',
    marginLeft: 54,
    justifyContent: 'center',
    [theme.breakpoints.down('sm')]: {
      marginLeft: 0,
      marginTop: 24,      
    },
  },
  movieTitleInfo:{
    marginTop: 24,
    [theme.breakpoints.down('sm')]: {
      marginLeft: 0,
      marginTop: 24,
      justifyContent: 'center'            
    },
  },
  section:{
    display: 'flex',
    marginTop: 32,
    [theme.breakpoints.down('sm')]: {
      flexDirection: 'row',
      padding: '0px'
    },
  },
  recomm:{
    marginTop: 32,
    padding: '0px 100px',
    [theme.breakpoints.down('sm')]: {
      marginTop: 18,
      padding: '0px 16px',
      justifyContent: 'center'
    },
  },
  infoItem:{
    marginRight: 24,
    [theme.breakpoints.down('sm')]: {
      marginRight: 8,
    },
  },
  moviInfo_label:{
    marginBottom: 24,    
  },
  moviInfo_overview:{
    paddingRight:20,
    [theme.breakpoints.down('sm')]: {
      padding: 0,
      marginBottom: 24
    },
  }
}));

export default function movieInfo() {
  const classes = useStyles();    
  const router = useRouter();

  const {search,error, datas} = getSearch(router.query.search);
  
  
  if(!search){       
    return ( <div> { console.log('nothing') }</div> )
  }else{    
    // return <div> {console.log(search)} {datas}</div>
    return (
      <div >
        <Head>        
          <meta name="description" content="Generated by create next app" />        
          <title>Moviebot</title>
        </Head>
        <AppBarBar></AppBarBar>
        <Jumbotron></Jumbotron>
        <main>
        {/* recommendation list */}
        <Grid container className={classes.recomm}>
          <Grid item xs={12}>
            <ListItem title="Recommendation" list="recommendation" type="movie" datas={search}></ListItem>
          </Grid>
        </Grid>
        </main>

        <footer>
          
        </footer>
      </div>        
    )    
  }
}
