import Head from 'next/head'

import AppBarBar from '../component/AppBarBar'
import Jumbotron from '../component/Jumbotron'
import ListItem from '../component/ListItem'

import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles((theme) => ({
  main: {    
    paddingLeft: 20,
    [theme.breakpoints.down('sm')]: {      
      padding: 16,
    },    
  },

}));

export default function Home(props) {
  const classes = useStyles();

  return (
    <div >
      <Head>
        <title>Moviebot</title>
        <meta name="description" content="Generated by create next app" />        
      </Head>
      <AppBarBar></AppBarBar>
      <Jumbotron></Jumbotron>
      <main className={classes.main}>
       <ListItem title="Popular Movie" type='movie' datas={props.popularMovie}></ListItem>
       <ListItem title="Popular TV Series" type='tv' datas={props.popularTv}></ListItem>
       <ListItem title="Trailer" type='trailer'></ListItem>
       <ListItem title="New Movies" type='movie' datas={props.latestMovie}></ListItem>
       <ListItem title="New TV Series"type='tv' datas={props.latestTv}></ListItem>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}

export async function getStaticProps() {  

  const resPopularMovie = await fetch('https://api.themoviedb.org/3/trending/all/day?api_key=ec4bdffc57939748a8ae19503628e514')
  const popularMovie = await resPopularMovie.json()

  const resPopularTv = await fetch('https://api.themoviedb.org/3/tv/popular?api_key=ec4bdffc57939748a8ae19503628e514&language=en-US&page=1')
  const popularTv = await resPopularTv.json()

  const resLatestMovie = await fetch('https://api.themoviedb.org/3/movie/upcoming?api_key=ec4bdffc57939748a8ae19503628e514&language=en-US&page=1')
  const latestMovie = await resLatestMovie.json()

  const resLatestTv = await fetch('https://api.themoviedb.org/3/tv/popular?api_key=ec4bdffc57939748a8ae19503628e514&language=en-US&page=1')
  const latestTv = await resLatestTv.json()

  if (!popularMovie && !popularTv && !latestMovie && !latestTv) {
    return {
      notFound: true,
    }
  }

  return {    
    props: { 
      popularMovie, popularTv, latestMovie, latestTv
     }, // will be passed to the page component as props
  }
}
